{% set name = "datreant" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/datreant-{{ version }}.tar.gz
  sha256: da206b21c3eb713adedf0ea18f747fc9d3f9d049eebada3b2ee34f2dd8b688fb

build:
  noarch: python
  entry_points:
    - datreant_07to1=datreant.scripts.datreant_07to1:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - asciitree
    - scandir
    - fuzzywuzzy
    - python-levenshtein
    - pyparsing >=3.0

test:
  imports:
    - datreant
  commands:
    - pip check
    - datreant_07to1 --help
  requires:
    - pip

about:
  home: http://datreant.org/
  license: BSD-3-Clause
  license_file: LICENSE
  summary: persistent, pythonic trees for heterogeneous data

extra:
  recipe-maintainers:
    - dotsdl
    - kain88-de
