travis:
  secure:
    BINSTAR_TOKEN: H3hJbQsRkS4/00M+1UEGpUDRkfoTl9NXFwGd+4aCY55J131ulM4uiUZnSY/QTyNYVN6Ii5emgyc2BQP+u32YNRqlWQscu2g/lNadc6tnqsBglzQiSEGpXZ7g8phqvVwI5sykIeHppU5xC03/O9O/fNzF0c12krUzfmKH/65G3e8ES7q+MLB6xZJGw0n0YBdvr6kojRc9zC+tAHZZAqD71X34tzq65FXTE0zUXsQkMty5hoY6cL62340nmdKZzHxory5iimE31bow6DV1INB+oNOmIjD3o7kuwFieuqlN66XcIFRYzXadpisEcEEQw//ezvbnLJWYqZIxrqANb9nIYMpp6rTZEfWmrpSiwtWVtOUj54ZtAXGxvaQh50ouhuPQVa61Hs+jdx5tFdVxbBETHiMa5iuhJtWQ+hZnUTFlPaN1dPSmhYh/6TUSniCpKXkGHIrAlYU+zaO6ofGp9dKLeXflyzkXeoq+yD3p8SRWbxIz0bpJe4jaVjrd4mZACTUXi+ZxwLzy5YszrUDSghl8fDHizuQT9wfZwmGwVOfjihNp7izzB73iqVO77sVzC4r2W0ZHZT4bJFtcVSp/qkAcCyfG81PnAGxebDbdgK17Qs5YuJ1KzpnHHdmvik6Ijq1HpvB1813kn4ER3RHhkHcJdPCxSLUIST3NsG7L6CvzuR4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
