travis:
  secure:
    BINSTAR_TOKEN: BveYp2DZdjyn82jJaCp+6vM7fg8CQ0nhkv8zu08fjiTz2hlzwDuS5fhjPu2B5gOSkNvq6eFu4+MtiJjuVDXv3gUw6M3Z+sBNkc/J5KPOutc4kGhDsxJ31vWgxmdAHQ9Ycd0YZwr70P13HEN5KkBmZ6CJuWfQd3BkkLZl9ksZc9nB9ehrelPfMT9TRtYd45mIz2oyD+yuAkOlzPm9KfNu6OmA/MUx3kKOw6UmIYlhsNtN5AGkkT5zaRtJOdY7WiPY1pSzLqJJ7qC/t8S+DCkp0nHzGfpvIRqoU4HsHtcNatktitj4yrvFIUBPV0QE1ipL4s5HBFQM8Y2Uw8kv8I0Qb5i8LqAYCf2LyBb5RDOhq+6mUVilw+NmdwJ34/ykQj2EvqwOaW1cZ0liSCg6sI2uzwYSAuGc7HEd55KMKZ80vX7bmJJDZSGd6yz6AT8beoBtPVn3av/WEw5pVIjSyE+sORiHxy04lmG7G1FbB64qkK92cpPZ81iDCFO/u7QiBCP1LAj+fcSoDZ4fM8ylkKCKBafp/Rmaul5vxtaZSMxhrMJCy8fwv5mR+0c8L2ERC3eM+MRS2nbffUtdNFj2aLMhRihiorkoXgjhrgT/2WqEtKzXH+UsJCrsyDuwpTnCMupQd+3R7CxCqblYO7BjxfDfeyYTKt92Qbsv6d5GXE9gEDg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
